name: Scan Jupyter Notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * 0" # optional weekly scan

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # required for CodeQL
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: [sql, python]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Extract SQL from notebooks
        run: |
          pip install jq
          python extract_sql.py

      # Example: use sqlfluff for linting
      - name: Lint SQL
        run: |
          pip install sqlfluff
          sqlfluff lint sql_extracted

      # --- Convert all .ipynb notebooks to .py files ---
      - name: Convert notebooks to Python
        run: |
          pip install nbconvert
          mkdir -p notebooks_processed
          for nb in $(find . -name '*.ipynb'); do
            echo "Converting $nb"
            jupyter nbconvert --to python "$nb" --output-dir notebooks_processed
            echo "Converted $nb to notebooks_processed/$(basename "${nb%.ipynb}.py")"
          done
          # copy converted files back to the workspace root for scanning
          rsync -a notebooks_processed/ .

      - name: Run Ruff linter
        run: |
          pip install ruff
          ruff check notebooks_processed

      # --- Run CodeQL on the converted Python ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
