name: Scan Jupyter Notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0" # optional weekly scan

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # required for CodeQL
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: ["python"] # we treat notebooks as Python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # --- Convert all .ipynb notebooks to .py files ---
      - name: Convert notebooks to Python
        run: |
          pip install nbconvert
          mkdir -p notebooks_py
          for nb in $(find . -name '*.ipynb'); do
            echo "Converting $nb"
            jupyter nbconvert --to script "$nb" --output-dir notebooks_py
            echo "Converted $nb to notebooks_py/$(basename "${nb%.ipynb}.py")"
          done
          # copy converted files back to the workspace root for scanning
          rsync -a notebooks_py/ .

      # --- Run CodeQL on the converted Python ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Lint code base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON: true # enable Python checks
          VALIDATE_MARKDOWN: false
