name: "CodeQL for Jupyter Notebooks"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: "0 0 * * 0" # Weekly scan

jobs:
  codeql-analysis:
    name: CodeQL Analysis for IPYNB
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: ["python"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality, security-extended

      - name: Extract and Convert Jupyter Notebooks
        run: |
          # Install required tools
          pip install nbconvert
          mkdir -p notebooks_py

          # Convert all .ipynb files to .py for CodeQL analysis
          echo "Converting Jupyter notebooks to Python scripts..."
          find . -name "*.ipynb" -type f | while read notebook; do
            echo "Converting $notebook"
            jupyter nbconvert --to script "$nb" --output-dir notebooks_py
          done

           # copy converted files back to the workspace root for scanning
          rsync -a notebooks_py/ .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:python"
